#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Usage: ./launch name_key path_to_file"
	exit 1
fi


KEY=$1
PATH_FILE=$2


DATA=()
echo "This will take 2-4 mins"

####install everything on local host#

# ./install_required_ec2

#######################################


while read output; do
	DATA+=($output)
done < <(python create_aws.py $KEY )

DNS=${DATA[0]}
echo $DNS
echo ${DATA[1]} > id.log


chmod 600 $PATH_FILE

scp -o StrictHostKeyChecking=no -r -i $PATH_FILE . ubuntu@$DNS:

ssh -o StrictHostKeyChecking=no -i $PATH_FILE ubuntu@$DNS '   cd bottle-0.12.7/; ./install_required_ec2; python run_backend_test.py; 
./tmux-host ; 	'  

# ssh -o StrictHostKeyChecking=no -i $PATH_FILE ubuntu@$DNS ' ./tmux-host	'


echo ${DATA[0]}
echo ${DATA[1]}